# -*- coding: utf-8 -*-
"""NLP-Hack

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MyOMbiF6bMAAquHZvEhNcNOTh8As5smY
"""

#Import libraries and twitter api auth
import tweepy
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
from wordcloud import WordCloud

consumer_key = "11CYnOi8oLFbiI44peyTRMRWi"
consumer_secret = "TzjB4qPzqwVZ74TVxC3St0rrRdamiMigGeoKurXY3IOPbzkSMn"
access_token = "1303429505256574976-dSaxtB5kpaDuYvj6zSXHQ4JBhuHynq"
access_token_secret = "zEKUTxTJgNINwJP8kAuhy55kwLZb5g1zq9Snsic0YLusA"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

#Scrape out usernames from homepage of twitter
public_tweets = api.home_timeline()

username = []
for tweet in public_tweets:
  username.append(tweet.user.screen_name)
print(username)

#Create a pandas dataframe of the obtained usernames
df = pd.DataFrame(username) 
df